---
# 1. Infrastructure Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: raju-infrastructure
  namespace: flux-system
spec:
  interval: 1m
  path: ./gitops/k8s-manifests/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

---
# 2. Application HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: raju-stack
  namespace: raju
spec:
  interval: 1m
  chart:
    spec:
      chart: ./gitops/k8s-manifests/applications
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    global:
      tag: "v26.100.9"  # Script isse update karega
      images:
        auth-service: "2024dock/auth-service:1.0.14"
        order-service: "2024dock/order-service:1.0.14"
        product-service: "2024dock/product-service:1.0.14"
        frontend: "2024dock/frontend:1.0.14"
