apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecom-postgres-pvc
  namespace: raju
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecom-elastic-pvc
  namespace: raju
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi