apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: raju-stack
  namespace: raju
spec:
  interval: 1m

  chart:
    spec:
      chart: ./gitops/k8s-manifests/applications
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system

  valuesFrom:
    - kind: ConfigMap
      name: raju-stack-values
      valuesKey: values.yaml