global:
  version: "v26.100.8"

authService:
  image: "2024dock/auth-service"
  tag: "1.0.13"

frontend:
  image: "2024dock/frontend"
  tag: "1.0.13"

orderService:
  image: "2024dock/order-service"
  tag: "1.0.13"

productService:
  image: "2024dock/product-service"
  tag: "1.0.13"
