# Global configuration used across all templates
global:
  tag: "v26.100.5" # Yahan se tum version change karoge aur saari services update ho jayengi

# Microservices specific image names
authService:
  image: "2024dock/auth-service"

frontend:
  image: "2024dock/frontend"

orderService:
  image: "2024dock/order-service"

productService:
  image: "2024dock/product-service"